spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:shop;Mode=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect