server:
  port: 8060
  servlet:
    context-path: /official

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect