server:
  port: 8070
  servlet:
    context-path: /reader

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true