server:
  port: 5555

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080" # адрес фронт сервиса
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: reader-service
          uri: http://localhost:8070/
          predicates:
            - Path=/reader/**
          filters:
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8090/
          predicates:
            - Path=/auth/**
          filters:
            - JwtAuthFilter
        - id: official-service
          uri: http://localhost:8060/
          predicates:
            - Path=/official/**
          filters:
            - JwtAuthFilter
        - id: admin-service
          uri: http://localhost:8050/
          predicates:
            - Path=/admin/**
          filters:
            - JwtAuthFilter
        - id: personalData-service
          uri: http://localhost:48884/
          predicates:
            - Path=/personal-data/**
          filters:
            - StripPrefix=1
            - JwtAuthFilter
jwt:
  secret: RIzJy0x4uGqOztmNB24aI6cyW8FL9+yD0O5TVte5UMRvG9ZKpjFHtxAYNraaADlR
