server:
  port: 8188
  servlet:
    context-path: /auth
jwt:
  secret: RIzJy0x4uGqOztmNB24aI6cyW8FL9+yD0O5TVte5UMRvG9ZKpjFHtxAYNraaADlR
  lifetime: 3600000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect