server:
  port: 8090
  servlet:
    context-path: /auth
    session:
      tracking-modes: cookie
jwt:
  secret: RIzJy0x4uGqOztmNB24aI6cyW8FL9+yD0O5TVte5UMRvG9ZKpjFHtxAYNraaADlR
  lifetime: 60m

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect