server:
  port: 48884
  error:
    include-message: always
    include-stacktrace: ON_PARAM

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:library;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl.auto: validate
        globally_quoted_identifiers: true
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration/mysql
    enabled: true

jwt:
  lifetime: 60m