server:
  port: 48884
  error:
    include-message: always
    include-stacktrace: ON_PARAM

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personal_data
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true
        hbm2ddl.auto: validate
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration/mysql
    enabled: true
#    locations: classpath:db/migration/postgresql